# Generated by Django 5.2.8 on 2025-12-10 16:19
from __future__ import annotations

import json
from pathlib import Path

from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    basemap_model = apps.get_model('core', 'Basemap')
    default_basemaps_file = Path(settings.BASE_DIR, 'geoinsight', 'core', 'models', 'basemaps.json')
    with default_basemaps_file.open() as f:
        default_basemaps = json.load(f)
        for default_basemap in default_basemaps:
            name = default_basemap.get('name')
            style = default_basemap.get('style')
            if name is not None and style is not None:
                basemap_model.objects.create(
                    name=name,
                    style=style,
                )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0016_dataset_owner_and_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basemap',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('style', models.JSONField()),
            ],
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
