# Generated by Django 5.2.9 on 2026-02-04 15:25
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_merge"),
    ]

    operations = [
        migrations.AddField(
            model_name="colorconfig",
            name="use_feature_props",
            field=models.BooleanField(default=True),
        ),
    ]
