# Generated by Django 5.2.9 on 2026-02-25 18:34
from __future__ import annotations

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import s3_file_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_non_null_text_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="View",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("thumbnail", s3_file_field.fields.S3FileField()),
                ("theme", models.CharField(default="light", max_length=10)),
                ("current_analysis_type", models.CharField(blank=True, max_length=25)),
                ("left_sidebar_open", models.BooleanField(default=False)),
                ("right_sidebar_open", models.BooleanField(default=False)),
                ("map_zoom", models.IntegerField(null=True)),
                (
                    "map_center",
                    django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
                ),
                ("panel_arrangement", models.JSONField(blank=True, null=True)),
                ("selected_layer_order", models.JSONField(blank=True, null=True)),
                ("selected_layer_styles", models.JSONField(blank=True, null=True)),
                (
                    "current_basemap",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="core.basemap",
                    ),
                ),
                (
                    "current_chart",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="core.chart",
                    ),
                ),
                (
                    "current_network",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="core.network",
                    ),
                ),
                (
                    "current_result",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="core.taskresult",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="core.project",
                    ),
                ),
                ("selected_layers", models.ManyToManyField(related_name="views", to="core.layer")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("project", "name"), name="uniqueviewname")
                ],
            },
        ),
    ]
