# Generated by Django 5.2.9 on 2026-03-16 14:42
from __future__ import annotations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_view_states"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskresult",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True, related_name="task_subscriptions", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
