name: ci
on:
  pull_request:
  push:
    branches:
      - master

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install tox
      - name: Lint
        run: tox -e lint

  lint-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: |
            docker-compose.yml
            docker-compose.override.yml
          services: |
            web
          test-container: web
          test-command: "npm run lint"

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: |
            docker-compose.yml
            docker-compose.override.yml
          services: |
            django
            celery
            postgres
            minio
            rabbitmq
          test-container: django
          test-command: "tox -e test"

  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: |
            docker-compose.yml
            docker-compose.override.yml
          services: |
            django
            celery
            postgres
            minio
            rabbitmq
          test-container: django
          test-command: "tox -e check-migrations"
